language: php
dist: xenial

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - COMPOSER_ALLOW_XDEBUG=0
    - SYMFONY_DEPRECATIONS_HELPER='weak_vendors'

jobs:
  include:
    - stage: test
      name: "Test installing the lowest dependencies"
      php: 7.2
      install:
        - phpenv config-rm xdebug.ini || true
        - composer update --prefer-lowest --prefer-stable --no-interaction --no-suggest
      script:
        - php vendor/bin/phpunit

    - stage: test
      php: 5.6
      install:
        - phpenv config-rm xdebug.ini || true
        - composer update --no-interaction --no-suggest
      script:
        - php vendor/bin/phpunit

    - stage: test
      php: 7.0
      install:
        - phpenv config-rm xdebug.ini || true
        - composer update --no-interaction --no-suggest
      script:
        - php vendor/bin/phpunit

    - stage: test
      php: 7.1
      install:
        - phpenv config-rm xdebug.ini || true
        - composer update --no-interaction --no-suggest
      script:
        - php vendor/bin/phpunit

    - stage: test
      php: 7.2
      install:
        - phpenv config-rm xdebug.ini || true
        - composer update --no-interaction --no-suggest
      script:
        - php vendor/bin/phpunit

    - stage: test
      php: 7.3
      install:
        - phpenv config-rm xdebug.ini || true
        - composer update --no-interaction --no-suggest
      script:
        - phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml
      after_script:
        - php vendor/bin/php-coveralls -o coveralls-upload.json -x coverage.xml

    - stage: test
      php: nightly
      install:
        - phpenv config-rm xdebug.ini || true
        - composer update --no-interaction --no-suggest
      script:
        - php vendor/bin/phpunit

  allow_failures:
    - php: nightly
